### ISSUE TITLE
Upgrade to Unity 2019 and IL2CPP Android for ARM64 Support?

### ISSUE THREAD

**Issue by GilbertoBitt** [LightBuzz/Azure-Unity#1]
**Is your feature request related to a problem? Please describe.**
according to google "[Starting August 1, 2019, your apps published on Google Play will need to support 64-bit architectures.](https://developer.android.com/distribute/best-practices/develop/64-bit)". So updating is necessary. and only on unity 2019 we can compile to arm64 and only using app bundle and on IL2CPP.

**Describe the solution you'd like**
Upgrade to 2019 and upgrade sqlite library to be able to compile on app bundle and ARM64

**Describe alternatives you've considered**
alternative for me is updating an old version of [sqlite repository](https://github.com/robertohuertasm/SQLite4Unity3d) for unity and update they version of [sql-net](https://github.com/praeclarum/sqlite-net). or just update the libary to major plataform to user [sql-net](https://github.com/praeclarum/sqlite-net)

**Additional context**

**Comment by gmakoudi** [comment]
Thank you for your feedback. Upgrading to Unity 2019 is in our pipeline.

**Comment by gmakoudi** [comment]
The issue is resolved. You can find the latest unity package [here](https://github.com/LightBuzz/Azure-Unity/releases/latest).
