### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by erinloy** [LightBuzz/Azure-Unity#3]
It would be of great help if you could demonstrate authentication against App Service using the [EasyAuth](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization) mechanism.  This seems to be where most code/articles/tutorials I've found tend to stop.  In my case, I need to authenticate against Google in a platform independent way (mobile/desktop/webgl).

**Comment by gmakoudi** [comment]
Thank you very much for your feedback. You are right that there is a gap in this area. It is something that we will be writing about (https://lightbuzz.com/blog/). 

As far as Google authentication is concerned here is a brief list of the steps that you need to follow:
1. First, you need to configure your Azure Mobile App to authenticate with Google.
2. Then you need to set your client to request authentication from Google. 
3. After getting a valid response, your client just have to pass the id_token from the response to LoginAsync.
```
JObject access = new JObject();
access.Add("access_token", "testtodolightbuzz");
access.Add("id_token", token);
MobileServiceUser user = await azureClient.LoginAsync(MobileServiceAuthenticationProvider.Google, access);
```
4. Finally, make sure that you store the UserId and the AuthenticationToken to your MobileServiceClient and from now on all the requests that need authentication will use it.
```
azureClient.CurrentUser.UserId = user.UserId;
azureClient.CurrentUser.MobileServiceAuthenticationToken = user.MobileServiceAuthenticationToken;
```

That should do the trick. Stay tuned for updates!
